# fly.toml app configuration file generated for sf7-flyio-example on 2023-12-16T15:23:51+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sf7-flyio-example"
primary_region = "nrt"
console_command = "php /var/www/html/bin/console"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.3"

[env]
  APP_RUNTIME = '\App\FlySymfonyRuntime'
  APP_ENV = "prod"
  APP_SECRET = "a1b2c3d4e5f6g7h8i9j0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
